[project]
name = "001-dsa-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sangeeth Sadanand", email = "sadanand.sangeeth@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
]

[project.scripts]
001-dsa-python = "001_dsa_python:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
